better error handler
KevinMRmz/evat-backend pull request #7
Opened 2023-01-20 18:53 UTC by KevinMRmz

Better way to handle errors

2023-01-20 19:26 UTC, JavierRuvalcaba requested changes

2023-01-20 19:26 UTC, JavierRuvalcaba commented on .env
> +MAX_PATIENTS_FOR_NURSE=6
Remove this file and add a `.env.example` instead.
The content of the `.env.example` should be like this: 

```
JWT_SECRET=CHANGE_ME
TOKEN_DURATION=CHANGE_ME
MAX_PATIENTS_FOR_NURSE=CHANGE_ME
```

2023-01-20 19:26 UTC, JavierRuvalcaba commented on services/patient-service/patient-service.js
> +    }
We can be more specific. The function is to return the patients of a nurse, so change `employee` word to `nurse`

```suggestion
    if (!idNurse) {
      throw new BadRequestError("Please provide a Nurse id");
    }

    const nurse = await EmployeeModel.findById(idNurse);

    if (!nurse) {
      throw new NotFoundError("Nurse was not found");
    }
```

2023-01-20 19:26 UTC, JavierRuvalcaba commented on services/patient-service/patient-service.js
> +
Validate first if the nurse exists or if the idNurse correspond to a nurse. After that validate if the nurse has already 6 patients or not.

```suggestion
    const employee = await EmployeeModel.findById(idNurse);

    if (employee.role !== "NURSE") {
      throw new BadRequestError(
        "The Employee you're trying to set is not a nurse"
      );
    }
    
    const patients = await this.returnNursePatients(idNurse);

    if (patients.length >= parseInt(process.env.MAX_PATIENTS_FOR_NURSE)) {
      throw new BadRequestError("This nurse can only have 6 patients or less");
    }
```

2023-01-20 19:26 UTC, JavierRuvalcaba commented on services/record-service/notifications-service.js
> +      throw new BadRequestError("Please provide an Doctor ID");
```suggestion
      throw new BadRequestError("Please provide a Doctor ID");
```

2023-01-20 19:26 UTC, JavierRuvalcaba commented on services/record-service/notifications-service.js
> +      throw new BadRequestError("Please provide an Doctor ID");
```suggestion
      throw new BadRequestError("Please provide a Doctor ID");
```

2023-01-20 19:26 UTC, JavierRuvalcaba commented on services/record-service/notifications-service.js
> +      throw new BadRequestError("Please provide a Id for transmitter");
```suggestion
      throw new BadRequestError("Please provide a Nurse Id");
```

2023-01-23 18:15 UTC, pedro123-67we submitted a review, later dismissed
good job!!!!

2023-01-23 18:24 UTC, JavierRuvalcaba requested changes

2023-01-23 18:24 UTC, JavierRuvalcaba commented on services/patient-service/patient-service.js
> +      throw new BadRequestError("Please provide an Nurse id");
```suggestion
      throw new BadRequestError("Please provide a Nurse id");
```

2023-01-23 18:29 UTC, JavierRuvalcaba requested changes

2023-01-23 18:29 UTC, JavierRuvalcaba commented on .env
> +MAX_PATIENTS_FOR_NURSE=6
Also remove this file from the repo.

2023-01-24 16:59 UTC, JavierRuvalcaba approved these changes

2023-01-25 17:02 UTC, pedro123-67we approved these changes

2023-01-25 17:03 UTC, merged